# This docker compose file defines the setup described in
# https://docs.scion.org/en/latest/tutorials/deploy.html
name: "SCION Tutorial"

services:
  scion01:
    image: scion01:1.0
    container_name: scion01
    hostname: scion01
    networks:
      as_net_01: {}
      transit_net:
        ipv4_address: 10.100.0.11
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion02:
    image: scion02:1.0
    container_name: scion02
    hostname: scion02
    networks:
      as_net_02: {}
      transit_net:
        ipv4_address: 10.100.0.12
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion03:
    image: scion03:1.0
    container_name: scion03
    hostname: scion03
    networks:
      as_net_03: {}
      transit_net:
        ipv4_address: 10.100.0.13
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion04:
    image: scion04:1.0
    container_name: scion04
    hostname: scion04
    networks:
      as_net_04: {}
      transit_net:
        ipv4_address: 10.100.0.14
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion05:
    image: scion05:1.0
    container_name: scion05
    hostname: scion05
    networks:
      as_net_05: {}
      transit_net:
        ipv4_address: 10.100.0.15
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion06:
    image: scion06:1.0
    container_name: scion06
    hostname: scion06
    networks:
      as_net_06: {}
      transit_net:
        ipv4_address: 10.100.0.21
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion07:
    image: scion07:1.0
    container_name: scion07
    hostname: scion07
    networks:
      as_net_07: {}
      transit_net:
        ipv4_address: 10.100.0.22
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion08:
    image: scion08:1.0
    container_name: scion08
    hostname: scion08
    networks:
      as_net_08: {}
      transit_net:
        ipv4_address: 10.100.0.23
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion09:
    image: scion09:1.0
    container_name: scion09
    hostname: scion09
    networks:
      as_net_09: {}
      transit_net:
        ipv4_address: 10.100.0.24
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion10:
    image: scion10:1.0
    container_name: scion10
    hostname: scion10
    networks:
      as_net_10: {}
      transit_net:
        ipv4_address: 10.100.0.25
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion11:
    image: scion11:1.0
    container_name: scion11
    hostname: scion11
    networks:
      as_net_11: {}
      transit_net:
        ipv4_address: 10.100.0.31
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion12:
    image: scion12:1.0
    container_name: scion12
    hostname: scion12
    networks:
      as_net_12: {}
      transit_net:
        ipv4_address: 10.100.0.32
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion13:
    image: scion13:1.0
    container_name: scion13
    hostname: scion13
    networks:
      as_net_13: {}
      transit_net:
        ipv4_address: 10.100.0.33
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion14:
    image: scion14:1.0
    container_name: scion14
    hostname: scion14
    networks:
      as_net_14: {}
      transit_net:
        ipv4_address: 10.100.0.34
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
  scion15:
    image: scion15:1.0
    container_name: scion15
    hostname: scion15
    networks:
      as_net_15: {}
      transit_net:
        ipv4_address: 10.100.0.35
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /home/shared:/shared
    tmpfs:
      - /run
      - /run/lock
networks:
# ISD 01
  as_net_01:
    ipam:
      config:
        - subnet: 10.10.1.0/24
  as_net_02:
    ipam:
      config:
        - subnet: 10.10.2.0/24
  as_net_03:
    ipam:
      config:
        - subnet: 10.10.3.0/24
  as_net_04:
    ipam:
      config:
        - subnet: 10.10.4.0/24
  as_net_05:
    ipam:
      config:
        - subnet: 10.10.5.0/24
  # ISD 02
  as_net_06:
    ipam:
      config:
        - subnet: 10.20.1.0/24
  as_net_07:
    ipam:
      config:
        - subnet: 10.20.2.0/24
  as_net_08:
    ipam:
      config:
        - subnet: 10.20.3.0/24
  as_net_09:
    ipam:
      config:
        - subnet: 10.20.4.0/24
  as_net_10:
    ipam:
      config:
        - subnet: 10.20.5.0/24
  # ISD 03
  as_net_11:
    ipam:
      config:
        - subnet: 10.30.1.0/24
  as_net_12:
    ipam:
      config:
        - subnet: 10.30.2.0/24
  as_net_13:
    ipam:
      config:
        - subnet: 10.30.3.0/24
  as_net_14:
    ipam:
      config:
        - subnet: 10.30.4.0/24
  as_net_15:
    ipam:
      config:
        - subnet: 10.30.5.0/24
  # transit_net simulates a Tier 1 network the ASes are all running within.
  transit_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24
